### ISSUE TITLE
!ilvls fungerer ikke

### ISSUE THREAD

**Issue by vilrolf** [vilrolf/discordwowbot#1]
ReferenceError: avgItemLvl is not defined
wowbot_test_1  | [2018-08-02 20:57:50]      at Object.exports.run (/usr/src/app/commands/wow/ilvls.js:5:30)
wowbot_test_1  | [2018-08-02 20:57:50]      at msg.validateArgs.then (/usr/src/app/node_modules/komada/src/events/message.js:73:15)
wowbot_test_1  | [2018-08-02 20:57:50]      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by vilrolf** [comment]
Tja. Må faktisk få ut noe informasjon der. Er jo ingengting nyttig. Tror tanken min var å skrive ut alle i rett rekkefølge

**Comment by vilrolf** [comment]
Kanksje vi kan ha !chars ilvl
istedenfor?
